# Generated by Django 3.2 on 2022-09-22 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createjob',
            old_name='experience',
            new_name='post_title',
        ),
        migrations.RenameField(
            model_name='createjob',
            old_name='job_title',
            new_name='post_type',
        ),
        migrations.RenameField(
            model_name='createjob',
            old_name='job_type',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='no_of_vacancy',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='position',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='createjob',
            name='skills',
        ),
    ]
